version: '3.9'
services:
  app222:
    # build: .
    image: node:22.8.0
    container_name: app222
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: kakashi99
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
